import Head from 'next/head'
import Banner from '../components/Banner'
import Banner2 from '../components/Banner2'
import Header from '../components/Header'
import SmallCard from '../components/Smallcard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

export default function Home({ exploreData, cardData }) {
  return (
    <div className=' bg-black '>
      <Head>
        <title>Vika - Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Banner2 />
      {/* SmallCard */}
      <main className='w-10/12 mx-auto pt-12'>
        <h2 className='text-4xl font-semibold pb-4'>Inspiration for your next trip</h2>
        <div className='grid grid-cols-1 sm:grid-cols-2  lg:grid-cols-4'>
        {exploreData?.map(({img, distance, location})=>(
            <SmallCard
             key={img}
              img={img}
              location={location}
              distance={distance}/>
        )) }
        </div>
      </main>
      {/* MediumCard */}
      <section className='w-10/12 m-auto'>
        <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

        <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
          {cardData?.map (({img, title}) =>(
            <MediumCard
            key={img}
            img={img}
            title={title} />
          ))}
        </div>
      </section>
      {/* LargeCard */}
    <LargeCard
      img='https://links.papareact.com/4cj'
      title='The Greatest Outdoors'
      description='Wishlists curated by Airbnb.'
      buttonText='Get Inspired'
    />

    <Footer />
    </div>
  )
}

export async function getStaticProps() {
    const exploreData = await fetch('https://links.papareact.com/pyp').
    then(
      (res) => res.json()
    );
const cardData = await fetch('https://links.papareact.com/zp1').
then(res => res.json())

    return {
      props: {
        exploreData,
        cardData
      },
    };
}
